name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  flutter_login: ^5.0.0
  get: ^4.6.6
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  nested: ^1.0.0
  pull_to_refresh_flutter3: ^2.0.2
dev_dependencies:
  blackfoot_flutter_lint: ^2.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true